### ISSUE TITLE
//VAR DBG_ROWS_LIMIT = 20 does not change number of rows in the debugger

### ISSUE THREAD

**Issue by hcc-donder** [didierterrien/Power-BI-Sidetools#22]
When I specify //VAR DBG_ROWS_LIMIT = 20, I still get 30 rows in the debugger. I am using version 1.2.2 with the May 2021 (version 2.93.981.0 64-bit) version of Power BI Desktop.

**Comment by didierterrien** [comment]
Did you write debug instructions after a RETURN expression ?

**Comment by hcc-donder** [comment]
No. I have it like this:

    Measure name = 
    VAR variable1 = DISTINCTCOUNT( TableName[ColumnName] )
    //VAR DBG_ROWS_LIMIT = 20
    RETURN
        variable1

This still shows 30 rows.

**Comment by didierterrien** [comment]
I cannot reproduce the issue. I just tried with Contoso copying and pasting your measure (image below). I published version 1.2.3 today. Can you update and retry please ? 
If it's still not working, can you share a simple pbix ? You might also try to copy and paste the measure from above into the desktop in order to avoid any invisible character.

![image](https://user-images.githubusercontent.com/37301981/121900986-509f4a80-cd26-11eb-90cf-c0896fd10fd1.png)

**Comment by hcc-donder** [comment]
I installed the new version and it works correctly with the new version. Thank you.

**Comment by didierterrien** [comment]
Thank you for your contribution !
